Get sources command
InterLinked1/phreakscript pull request #18
Opened 2023-06-17 16:27 UTC by encbar5

This adds a new command to phreaknet, called "source", which will execute the steps for downloading and patching asterisk source code. This operates on the current working directory, instead of /usr/src. It is not necessary to execute this command as root, provided that the prerequisites of git and subversion are already installed. Code that also needs to be used by the "install" command has been factored out into a function called get_source. Man page files were also update to include the new command.
This command will probably not get used often by users, and is aimed a providing a way to consistently get source and patches for inclusion in a debian packaging system. 
The only existing command that should be affected by the changes is the "install" command. I have only regression tested the "install" command with -s -t -d flags, and with and without the -f flag.

2023-06-17 16:34 UTC, InterLinked1 requested changes
Thanks, looks good! Just a couple minor things...

2023-06-17 16:34 UTC, InterLinked1 commented on phreaknet.1.md
> +: Download source code only, without building or installing. This operates on the current working directory.
This makes it sound like only the original source is downloaded but not patched. I'd add that it is patched, unless --vanilla is use

2023-06-17 16:34 UTC, InterLinked1 commented on phreaknet.sh
> +		{ git --version >/dev/null && svn help >/dev/null; } || { echo "Please install git and subversion packages and try again."; exit 2; }
You can use the echoerr function here

2023-06-18 01:42 UTC, encbar5 commented
@InterLinked1 questions
1) do you care if I squash the fixes for your comments into the last commit, or do you want a new commit?
2) I didn't edit the changelog at the top of phreaknet.sh. Is that automated or do I need to put that in my pull request?

2023-06-18 01:46 UTC, InterLinked1 commented
> @InterLinked1 questions
> 
> 1. do you care if I squash the fixes for your comments into the last commit, or do you want a new commit?

Please squash them (the 2 commits you have now are fine since they do separate things, but these fixes should be part of that 2nd one).

> 2. I didn't edit the changelog at the top of phreaknet.sh. Is that automated or do I need to put that in my pull request?

It's not automated. If it's a noteworthy change, you'll have to add it to the top.
The svn stuff you don't need to mention; you can just note that the source command has been added.

2023-06-18 01:55 UTC, encbar5 commented
Ok comments addressed. Fair warning that I haven't actually tested putting the results of this into the debian packaging to see if it will work yet. I'm hoping I don't have to run any of the menuselect stuff here, and that the packaging 'make' will do that. So future adjustments might be needed. If you want to hold off until that is tested, then that's fine, I'm just not sure how long that part will take to figure out.

2023-06-18 01:58 UTC, merged